### ISSUE TITLE
Compute CSA prediction error

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/contrast-agnostic-softseg-spinalcord#67]
## Description

In the analysis of CSA, we want to compute the CSA error between the GT and the prediction for every image of the test set:

ABS(CSA_pred- CSA_GT)

### TODO

- [x] Set the same Y lim between methods
- [x] Validate to take GT csa_GT_soft_bin
- [x] For violin plot to compare all methods error, append all contrasts  in the same column instead of mean

**Comment by sandrinebedard** [comment]
## Here are some preliminary results:

### Error for `csa_monai_csaDiceL_160x224x96`:
![violin_plot_csa_percontrast_errorMONAI_avg_csa](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/71230552/6edc080c-7d9d-4deb-80d3-d2c8270048c3)


### Error for `ivado_avg_bin_no_crop`:
![violin_plot_csa_percontrast_errorIVADO_avg_bin](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/71230552/f2e7843e-25a4-4b89-be0a-d32e596d09bb)


### Error for `csa_nnunet_soft_avg_all_no_crop`:
![violin_plot_csa_percontrast_errornnUNet_avg_bin](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/71230552/353ca070-07fc-49d7-914d-9552c2fcb1cb)


### For all:
![violin_plot_csa_error_all](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/assets/71230552/56fefcc2-4347-49e9-bbd4-67fa1ae141c3)

**Note that for now it is not Binarized CSA soft GT that is used, this may change the results...**

**Comment by naga-karthik** [comment]
Thanks for creating these plots @sandrinebedard ! Just to clarify: 

> In the analysis of CSA, we want to compute the CSA error between the GT and the prediction for every image of the test set:
ABS(CSA_pred- CSA_GT)

This is the CSA of the _entire_ label right? Not just the CSA of C2-C3 levels?

**Comment by sandrinebedard** [comment]
> Thanks for creating these plots @sandrinebedard ! Just to clarify:
> 
> > In the analysis of CSA, we want to compute the CSA error between the GT and the prediction for every image of the test set:
> > ABS(CSA_pred- CSA_GT)
> 
> This is the CSA of the _entire_ label right? Not just the CSA of C2-C3 levels?

This is at C2-C3, you are right is would be good to compte the error on the entire mask, or slicewise.

**Comment by naga-karthik** [comment]
Closing as all tasks are done and we have the latest plots
